version: '2.1'

services:
  mysqladmin:
    image: mysql:5
    ports:
      - 3308:3306
    volumes:
      - ./etc/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./init:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: menu_admin
